[package]
name = "Simple_kernel"
version = "0.1.0"
edition = "2021"
authors = [
    "zyc <2357648739@qq.com>"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
qemu = []
board_k210 = []

[profile.release]
debug = true